### ISSUE TITLE
Failed to execute 'define' on 'CustomElementRegistry': the name "ssrs-reportviewer" has already been used with this registry

### ISSUE THREAD

**Issue by WUK29** [tycomo/ngx-ssrs-reportviewer#26]
Hi i have download this component and when i used in app.module.ts file it gives me error.

DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "ssrs-reportviewer" has already been used with this registry
    at CustomElementRegistry.target.<computed> [as define] (http://localhost:3035/dist/polyfills.js:10010:31)
    at new ReportViewerModule (http://localhost:3035/dist/main.js:301129:24)
    at _createClass (http://localhost:3035/dist/main.js:105957:20)
    at _createProviderInstance (http://localhost:3035/dist/main.js:105929:26)
    at initNgModule (http://localhost:3035/dist/main.js:105862:32)
    at new NgModuleRef_ (http://localhost:3035/dist/main.js:106589:9)
    at createNgModuleRef (http://localhost:3035/dist/main.js:106578:12)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (http://localhost:3035/dist/main.js:108409:12)
    at NgModuleFactory_.push.../node_modules/@angular/core/fesm5/core.js.NgModuleFactory_.create (http://localhost:3035/dist/main.js:109137:25)
    at MapSubscriber.project (http://localhost:3035/dist/main.js:165552:34)
![ssrs report viewer issue](https://user-images.githubusercontent.com/59955453/72509229-f1a38080-3868-11ea-93ab-8c188a17586c.png)

**Comment by Waleedsts** [comment]
@WUK29 i m also facing this issue. do you solve that ?

**Comment by sfohart** [comment]
I'm too...

```
core.js:4002 ERROR Error: Uncaught (in promise): NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "ssrs-reportviewer" has already been used with this registry
Error: Failed to execute 'define' on 'CustomElementRegistry': the name "ssrs-reportviewer" has already been used with this registry
    at CustomElementRegistry.target.<computed> [as define] (zone.js:2241)
    at new ReportViewerModule (ngx-ssrs-reportviewer.js:118)
    at _createClass (core.js:20279)
    at _createProviderInstance (core.js:20251)
    at initNgModule (core.js:20184)
    at new NgModuleRef_ (core.js:20893)
    at createNgModuleRef (core.js:20882)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:29847)
    at NgModuleFactory_.push../node_modules/@angular/core/fesm5/core.js.NgModuleFactory_.create (core.js:30555)
    at MapSubscriber.project (router.js:3598)
    at resolvePromise (zone.js:852)
    at resolvePromise (zone.js:809)
    at zone.js:913
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:26247)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
defaultErrorLogger @ core.js:4002
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:4050
next @ core.js:26759
schedulerFn @ core.js:23735
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:192
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:130
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:23719
(anonymous) @ core.js:26278
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:26215
onHandleError @ core.js:26278
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:395
push../node_modules/zone.js/dist/zone.js.Zone.runGuarded @ zone.js:164
_loop_1 @ zone.js:715
api.microtaskDrainDone @ zone.js:724
drainMicroTaskQueue @ zone.js:608
Promise.then (async)
scheduleMicroTask @ zone.js:584
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:413
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:258
scheduleResolveOrReject @ zone.js:900
ZoneAwarePromise.then @ zone.js:1040
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:26791
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:84
0 @ main.ts:12
__webpack_require__ @ bootstrap:84
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
```

**Comment by tycomo** [comment]
Issue is fixed with latest version.
