### ISSUE TITLE
ngx-ssrs-reportviewer 

### ISSUE THREAD

**Issue by jitendraPradhan** [tycomo/ngx-ssrs-reportviewer#5]
WARNING in ./node_modules/ngx-ssrs-reportviewer/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (D:\..\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (D:\..\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (D:\TFS PROJECTS\101 TFS PROJECTS\ANGULAR PROJECTS\\\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (D:\TFS PROJECTS\101 TFS PROJECTS\ANGULAR PROJECTS\\\node_modules\webpack\lib\Compiler.js:502:17)
    at D:\TFS PROJECTS\101 TFS PROJECTS\ANGULAR PROJECTS\\\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\TFS PROJECTS\101 TFS PROJECTS\ANGULAR PROJECTS\\\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (D:\TFS PROJECTS\101 TFS PROJECTS\ANGULAR PROJECTS\\\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ngx-ssrs-reportviewer/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ngx-ssrs-reportviewer/ngx-ssrs-reportviewer/ngx-ssrs-reportviewer.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/ngx-ssrs-reportviewer/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (D:\TFS PROJECTS\101 TFS PROJECTS\ANGULAR PROJECTS\\\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (D:\TFS PROJECTS\101 TFS PROJECTS\ANGULAR PROJECTS\\\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (D:\TFS PROJECTS\101 TFS PROJECTS\ANGULAR PROJECTS\\\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (D:\TFS PROJECTS\101 TFS PROJECTS\ANGULAR PROJECTS\\\node_modules\webpack\lib\Compiler.js:502:17)
    at D:\TFS PROJECTS\101 TFS PROJECTS\ANGULAR PROJECTS\\\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\TFS PROJECTS\101 TFS PROJECTS\ANGULAR PROJECTS\\\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (D:\TFS PROJECTS\101 TFS PROJECTS\ANGULAR PROJECTS\\\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ngx-ssrs-reportviewer/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ngx-ssrs-reportviewer/ngx-ssrs-reportviewer/ngx-ssrs-reportviewer.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by uncarlo** [comment]
I'm having the same error. I guess development on this library is dead?

**Comment by harinikprabhu** [comment]
Are there any other alternatives to display report viewer in Angular application? This library doesn't seem to work in Angular higher versions.
